services:
  app:
    platform: linux/amd64
    container_name: dev_workspace_app
    env_file:
      - .env
    image: ghcr.io/davirezendemota/dev-workspace:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WORKSPACE_CONFIG_PATH=/data/config.json
      - WORKSPACE_LOCAL_PROJECTS_ROOT=${WORKSPACE_LOCAL_PROJECTS_ROOT}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./workspace_data:/data
      - ${WORKSPACE_LOCAL_PROJECTS_ROOT}:/local-projects:ro
